name: Fill Results

on:
  schedule:
    - cron: "27 */6 * * *" # Run every 6 hours at the 27 minute mark
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-results-updater:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (master branch)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run results.py
      run: |
        cd codebase
        python3 -m results.results

    - name: Commit and push updated CSVs to master branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions@github.com"

        CSV_LIST="
          codebase/data/master_avg_bets.csv
          codebase/data/master_avg_full.csv
          codebase/data/master_mod_zscore_bets.csv
          codebase/data/master_mod_zscore_full.csv
          codebase/data/master_pin_bets.csv
          codebase/data/master_pin_full.csv
          codebase/data/master_zscore_bets.csv
          codebase/data/master_zscore_full.csv
          codebase/data/master_random_bets.csv
          codebase/data/master_random_full.csv
        "

        git add $CSV_LIST
        git commit -m "Update results - $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "Nothing to commit"

        git pull --rebase origin master

        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/asmith7654/paper-betting-tracker.git HEAD:master